**1. Import the numpy package under the name np (★☆☆)**

In [ ]:
import numpy as np

**2. Print the numpy version and the configuration (★☆☆)**

In [ ]:
print(np.__version__)
print(np.__config__)
np.show_config()

1.26.4
<module 'numpy.__config__' from '/usr/local/lib/python3.10/dist-packages/numpy/__config__.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name:

**3. Create a null vector of size 10 (★☆☆)**

In [ ]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**4. How to find the memory size of any array (★☆☆)**

In [ ]:
x = np.array([1, 2, 3])
print("Size of the array: ", x.size)
print("Memory size of one element array in size: ", x.itemsize)
print("Memory size of array in bytes: ", x.size * x.itemsize)

Size of the array:  3
Memory size of one element array in size:  8
Memory size of array in bytes:  24


**5. How to get the documentation of the numpy add function from the command line? (★☆☆)**

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
print(np.info(np.subtract))

subtract(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Subtract arguments, element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be subtracted from each other.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is c

**6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)**

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

**7. Create a vector with values ranging from 10 to 49 (★☆☆)**

In [ ]:
x = np.arange(10, 49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

**8. Reverse a vector (first element becomes last) (★☆☆)**

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = x[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x = np.flip(x)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)**

In [ ]:
x = np.arange(9).reshape(3, 3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)**

In [ ]:
x = [1, 2, 0, 0, 4, 0]
for i in range(len(x)):
  if x[i] != 0:
    print(i)

print(np.nonzero(x))

0
1
4
(array([0, 1, 4]),)


**11. Create a 3x3 identity matrix (★☆☆)**

In [ ]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**12. Create a 3x3x3 array with random values (★☆☆)**

In [ ]:
x = np.random.random((3, 3, 3))
x

array([[[0.83701955, 0.4199903 , 0.06590348],
        [0.42594071, 0.48119862, 0.30375047],
        [0.34191015, 0.70426652, 0.1339683 ]],

       [[0.43019721, 0.78371471, 0.31787186],
        [0.61018914, 0.40005422, 0.37067418],
        [0.32798282, 0.245637  , 0.48683777]],

       [[0.59138566, 0.09201567, 0.69796986],
        [0.51812285, 0.01578199, 0.41267768],
        [0.57296653, 0.71882343, 0.31626952]]])

**13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)**

In [ ]:
x = np.random.random((10, 10))
print(x)
print(np.min(x))
print(np.max(x))

[[0.12908561 0.02714198 0.65459404 0.11586297 0.30766301 0.52423653
  0.67520529 0.88689363 0.46721782 0.50454996]
 [0.78373682 0.09798663 0.36635634 0.89155119 0.04254311 0.09463933
  0.87724342 0.33432679 0.42347438 0.42820044]
 [0.71185368 0.40933039 0.36345412 0.44047831 0.05057374 0.21079607
  0.74915317 0.14898529 0.29300509 0.14689762]
 [0.18229099 0.10227989 0.02225898 0.5232675  0.06338763 0.47973556
  0.31585335 0.73801041 0.79407299 0.93160948]
 [0.18046854 0.32689873 0.4402905  0.20838441 0.45389662 0.12366095
  0.89531627 0.33513084 0.74506152 0.28876626]
 [0.46874358 0.96723419 0.01493414 0.89621291 0.61162294 0.27537421
  0.03415758 0.34377488 0.89562823 0.52604541]
 [0.67366839 0.47586241 0.46132387 0.20692699 0.09051878 0.81805223
  0.33090301 0.13691248 0.82143664 0.37421392]
 [0.84103166 0.50511627 0.7660655  0.1893337  0.19106244 0.37644971
  0.71558604 0.7610939  0.74203054 0.16270169]
 [0.53400611 0.55470801 0.48898799 0.12700705 0.25220638 0.53355071
  0.96730536

**14. Create a random vector of size 30 and find the mean value (★☆☆)**

In [ ]:
x = np.random.rand(30)
print(x)
print(np.mean(x))

[0.64068506 0.40008716 0.40172325 0.30565007 0.34456404 0.76701115
 0.82166376 0.14944972 0.23325711 0.55784912 0.43225444 0.69542618
 0.18480831 0.86403166 0.16021866 0.03020415 0.64714415 0.97659132
 0.06472005 0.42192937 0.34731991 0.26674384 0.61309398 0.08514559
 0.21445376 0.83535203 0.67869234 0.04893514 0.62174376 0.70218713]
0.450431206745893


**15. Create a 2d array with 1 on the border and 0 inside (★☆☆)**

In [ ]:
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**16. How to add a border (filled with 0's) around an existing array? (★☆☆)**

In [ ]:
x = np.ones((5, 5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
x = np.arange(25).reshape(5, 5)
x = np.pad(x, pad_width=1, mode='constant', constant_values=5)
print(x)

[[ 5  5  5  5  5  5  5]
 [ 5  0  1  2  3  4  5]
 [ 5  5  6  7  8  9  5]
 [ 5 10 11 12 13 14  5]
 [ 5 15 16 17 18 19  5]
 [ 5 20 21 22 23 24  5]
 [ 5  5  5  5  5  5  5]]


**17. What is the result of the following expression? (★☆☆)**

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

np.nan in set([np.nan])

0.3 == 3 * 0.1

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


**18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)**

In [ ]:
x = np.diag(1+np.arange(4), k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
x = np.diag(1 + np.arange(4), k=0)
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
x = np.diag(1 + np.arange(4), k=1)
print(x)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


**19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)**

In [ ]:
x = np.zeros((8, 8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)**

ravel :
- Purpose: To convert a multidimensional array into a 1D array (flatten it).
- Usage: numpy.ravel(a)
  - Parameters: a is the input array you want to flatten.
  - Returns: A flattened 1D view of the original array (if possible; otherwise, a copy).
  - Example:
    - Create a 2D array
    - array_2d = np.array([[1, 2], [3, 4]])
    - Use ravel to flatten it
    - flattened = np.ravel(array_2d)
    - print(flattened)  # Output: [1 2 3 4]

- unravel_index: Converts a flat index back into coordinates in the original multidimensional array.    

In [ ]:
x = np.unravel_index(99, (6, 7, 8))
print(x)
# Explanation : So the 99th element in the flattened version of the array is located at row 1, column 5, and depth 3 in the original 6x7x8 array.

(1, 5, 3)


**21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)**

In [ ]:
x = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
x = np.tile([0, 1], (2, 2))
x

array([[0, 1, 0, 1],
       [0, 1, 0, 1]])

**22. Normalize a 5x5 random matrix (★☆☆)**

- Min-Max Normalization rescales values to a range between 0 and 1.
- Z-Score Normalization standardizes values to have a mean of 0 and a standard deviation of 1.

In [ ]:
# Min-Max normalization
matrix = np.random.random((5, 5))
min_val = matrix.min()
max_val = matrix.max()
normalized_matrix = (matrix - min_val) / (max_val - min_val)
normalized_matrix

array([[0.74037373, 0.0970619 , 0.82700838, 1.        , 0.6871981 ],
       [0.11112765, 0.23709152, 0.03707814, 0.36363736, 0.18029761],
       [0.2706141 , 0.30975707, 0.11238261, 0.00262343, 0.38875886],
       [0.1210373 , 0.50871842, 0.56872805, 0.8938795 , 0.        ],
       [0.60248863, 0.73517019, 0.05425136, 0.44652873, 0.88191495]])

In [ ]:
# Z-Score Normalization
x = np.random.random((5, 5))
x = (x - np.mean(x) / np.std(x))
x


array([[-0.93278601, -1.67133988, -1.75025372, -1.85426539, -1.47807216],
       [-1.09455427, -0.89516663, -1.30182608, -1.10664602, -1.05115552],
       [-1.10535077, -1.02268427, -1.04784654, -1.19037647, -1.1374175 ],
       [-1.41118431, -1.88277887, -1.50399142, -1.40525418, -0.89318801],
       [-1.20979981, -1.55993376, -1.79653939, -1.42762952, -1.34039191]])

**23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)**

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


**24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)**

In [ ]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
c = np.dot(a, b)
print(c)

[[0.26719743 1.21223663]
 [0.54099522 1.57817939]
 [0.21731467 1.18111916]
 [0.3312739  1.78766981]
 [0.24431247 1.03104327]]


**25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)**

In [ ]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] *= -1
print(x)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


**26. What is the output of the following script? (★☆☆)**

In [ ]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


**27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)**

- Z**Z
- 2 << Z >> 2
- Z <- Z
- 1j*Z
- Z/1/1
- Z<Z>Z

In [ ]:
Z = np.array([1, 2, 3])
Z

array([1, 2, 3])

In [ ]:
Z**Z

array([ 1,  4, 27])

In [ ]:
2 << Z >> 2

array([1, 2, 4])

In [ ]:
Z <- Z

array([False, False, False])

In [ ]:
1j*Z

array([0.+1.j, 0.+2.j, 0.+3.j])

In [ ]:
Z/1/1

array([1., 2., 3.])

In [ ]:
ZZ

NameError: name 'ZZ' is not defined

In [ ]:
# Legal: Z**Z, 2 << Z >> 2, 1j * Z, Z / 1 / 1
# Illegal: Z <- Z, Z < Z > Z

**28. What are the result of the following expressions? (★☆☆)**

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-60-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-60-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-60-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


**29. How to round away from zero a float array ? (★☆☆)**

In [ ]:
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 7. -8.  2. -3. -9.  4. 10. -5. -1.  8.]
[ 7. -8.  2. -3. -9.  4. 10. -5. -1.  8.]


**30. How to find common values between two arrays? (★☆☆)**

In [ ]:
x = np.random.randint(0, 10, 10)
print(x)
y = np.random.randint(0, 10, 10)
print(y)
print(np.intersect1d(x, y))

[7 7 6 8 7 4 1 2 2 8]
[4 3 8 0 3 7 5 7 5 8]
[4 7 8]


**31. How to ignore all numpy warnings (not recommended)? (★☆☆)**

In [ ]:
# # Suicide mode on
# defaults = np.seterr(all="ignore")
# Z = np.ones(1) / 0

# # Back to sanity
# _ = np.seterr(**defaults)

# # Equivalently with a context manager
# with np.errstate(all="ignore"):
#     np.arange(3) / 0

**32. Is the following expressions true? (★☆☆)**

In [ ]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


<ipython-input-65-1a00e04f85bb>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
<ipython-input-65-1a00e04f85bb>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

**33. How to get the dates of yesterday, today and tomorrow? (★☆☆)**

 - UTC (Coordinated Universal Time)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print('Yesterday :', yesterday)
today     = np.datetime64('today')
print('Today :', today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print('Tomorrow :', tomorrow)

Yesterday : 2024-09-23
Today : 2024-09-24
Tomorrow : 2024-09-25


In [ ]:
from datetime import datetime

# Get the current date and time
current_time = np.datetime64('now', 's')  # 's' ensures precision up to seconds
print(current_time)


2024-09-24T03:40:04


In [ ]:
from datetime import datetime

# Get the current local date and time
now = datetime.now()

# Format the output to include the date and time with hours, minutes, and seconds
formatted_time = now.strftime("%Y-%m-%d %H:%M:%S")

print(formatted_time)


2024-09-24 03:42:22


**34. How to get all the dates corresponding to the month of July 2016? (★★☆)**

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
