**Import Libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

**Broadcasting**

- You can add a scalar to a vector, and numpy will add it to each element in vector.
  - x + a = (x)i + a
- Similarly you can add a vector to a matrix, and numpy will add the vector to each column of the matrix.

In [2]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [3]:
# We can add any value to whole array
print(x+4)

[5 6 7 8]


- This feature is called broadcasting.
- It only work with numpy.
- It will not work with normal python list.

Here,
- x = 1 2 3 4
- X = 10 20 30 40 40 50 60 70
- X + x = (10+1) + (40+1) (20+2) + (50+2) (30+3) + (60+3) (40+4) + (70+4)

In [4]:
x = np.array([1,2,3,4])
print(x)

X = np.array([[10,20,30,40],
             [40,50,60,70]])
print(X)
print(X + x)

[1 2 3 4]
[[10 20 30 40]
 [40 50 60 70]]
[[11 22 33 44]
 [41 52 63 74]]


**Matrix Multiplication**

This is perhaps one operation that you would use quite frequently in any ML/DL model. You should remember a few things about multiplication
- C = AB is only defined when the second dimension of A matches the first dimension of B
- Further, if A is of shape (m,n) and B of shape (n,p), then C is of shape (m,p)
- This operation is concretely defined as (C)i,j = (Summation)k (A)i,k (B)k,j
  - (C)i,j is computed by taking the dot product of i-th rwo of A with j-th column of B
- A more useful method to think of matrix multipllication is as "linear combination of columns" of A weighted by column entries of B
- Matrix multiplication is also referred as dot product
- Time Complexity of this matrix multiplication is: T(C) = O(n^3)

In [5]:
# If we want to do matrix multiplication then we will use dot()
A = np.array([[1,2],
             [3,4]])

B = np.array([[0,2],
             [3,2]])

C = np.dot(A,B)
print(C)

[[ 6  6]
 [12 14]]


**Hadamard Product - Element wise multiplication**

- Element wise multiplication A (circle symbol(inside circle (dot(symbol))) B
- Notice how numpy uses the * for this. Important to be careful, and not to confuse this with matrix multiplication

How is this working element wise multiplication. (Remember this is not matrix multiplication)
- 1x0 = 0, 2x2 = 4
- 3x3 = 9, 4x2 = 8

In [6]:
A = np.array([[1,2],
             [3,4]])

B = np.array([[0,2],
             [3,2]])
A*B

array([[0, 4],
       [9, 8]])