**Import Libraries**

In [1]:
import numpy as np
import matplotlib.pyplot as plt

**Norms**

- linalg : linear algebra
- ord : order
- inf : infinity

In [2]:
x = np.array([-3, 4])
print(x)

[-3  4]


In [3]:
# If we want to compute Lp1 Norm
# Here the output is 3 + 7(No square is done or under square root is taken in lp1)
lp1 = np.linalg.norm(x, ord=1)
print(lp1)

7.0


In [4]:
# If we want to compute Lp2 Norm
# Here the output is under root of 3 sq + 4 sq
lp2 = np.linalg.norm(x, ord=2)
print(lp2)

5.0


In [5]:
# If we want to compute Lp3 Norm
lp3 = np.linalg.norm(x, ord=3)
print(lp3)

4.497941445275415


In [6]:
# If we want to compute infinity norm
# Here the output is the largest value in the vector.
lpinf = np.linalg.norm(x, ord=np.inf)
print(lpinf)

4.0


**Determinants**

Here the output is:
- = 1*4 - 2*3
- = 4 - 6
- = -2

In [7]:
# If we want to calculate determinant of a matrix
A = np.array([[1,2],
             [3,4]])

np.linalg.det(A)

-2.0000000000000004

**Inverse**

In [8]:
# If we want to calculate inverse of a matrix
A = np.array([[1,2],
             [3,4]])
print(A)
Ainv = np.linalg.inv(A)
print(Ainv)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Here the output is something like
- A.A^-1 = I
  - 1 0
  - 0 1

In [9]:
# If we take a dot product of inverse matrix with A
# The output is something like identity matrix
print(np.dot(A,Ainv))

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [10]:
# If we want to compute Pseudo Inverse
A = np.array([[1,2],
             [3,4]])
print(A)
pinv = np.linalg.pinv(A)
print(pinv)
print(np.dot(A,pinv))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.00000000e+00 -6.66133815e-16]
 [ 1.77635684e-15  1.00000000e+00]]


In [11]:
A = np.array([[6,8],
             [3,4]])
print(A)
pinv = np.linalg.pinv(A)
print(pinv)
print(np.dot(A,pinv))

[[6 8]
 [3 4]]
[[0.048 0.024]
 [0.064 0.032]]
[[0.8 0.4]
 [0.4 0.2]]


**Linear Equations**

- Suppose, there are two equations
    - 2x1 + 3x2 = 8
    - 3x1 + 1x2 = 5
- We have to calculate the value for vector x = [x1, x2]
- Or we have to find the values of x1 and x2

In [12]:
a = np.array([[2,3], [3,1]])
b = np.array([8,5])

print(a)
print(b)

[[2 3]
 [3 1]]
[8 5]


Here the output is : x1 = 1, x2 = 2
- 2(1) + 3(2) = 8
- 3(1) + 1(2) = 5

In [13]:
np.linalg.solve(a, b)

array([1., 2.])