**Import Libraries**

In [1]:
import numpy as np

- rand : Random values in a given shape
- randn : Return a sample(or samples) from the "standard normal" distribution
- randint : Return random integers from low (inclusive) to high (exclusive)
- random : Return random floats in half-open interval(0.0, 1.0)
- choice : Generates a random sample from a given 1-D array
- shuffle : Shuffles the contentsof a sequence

**rand() - This function generates random numbers between 0 and 1**

In [2]:
a = np.random.rand()
print(a)

0.5579922522873494


In [3]:
aa = np.random.rand(5)
print(aa)

[0.01170372 0.97309743 0.22097095 0.96678708 0.09770364]


In [4]:
aaa = np.random.rand(3, 3)
print(aaa)

[[0.91866424 0.62139909 0.06416994]
 [0.89948923 0.99100907 0.63549058]
 [0.69700411 0.20324219 0.05304174]]


In [5]:
aaaa = np.random.rand(3, 3, 3)
print(aaaa)

[[[0.98546455 0.09096274 0.03089269]
  [0.57639651 0.11981652 0.37411129]
  [0.80748952 0.45071821 0.53036177]]

 [[0.46917956 0.5451613  0.6510544 ]
  [0.05119566 0.12837705 0.20708681]
  [0.2859222  0.30641301 0.82676559]]

 [[0.56652101 0.19915291 0.4240586 ]
  [0.42698251 0.84964754 0.02438536]
  [0.21686799 0.4462618  0.35589443]]]


In [6]:
# Round off the values upto .2f decimal place
a = np.round(a, 2)
aa = np.round(aa, 2)
aaa = np.round(aaa, 2)
aaaa = np.round(aaaa, 2)
print('First :', a)
print('Second :', aa)
print('Third :', aaa)
print('Fourth :', aaaa)

First : 0.56
Second : [0.01 0.97 0.22 0.97 0.1 ]
Third : [[0.92 0.62 0.06]
 [0.9  0.99 0.64]
 [0.7  0.2  0.05]]
Fourth : [[[0.99 0.09 0.03]
  [0.58 0.12 0.37]
  [0.81 0.45 0.53]]

 [[0.47 0.55 0.65]
  [0.05 0.13 0.21]
  [0.29 0.31 0.83]]

 [[0.57 0.2  0.42]
  [0.43 0.85 0.02]
  [0.22 0.45 0.36]]]


**randint() - This function generates +ve integers numbers**

In [7]:
b = np.random.randint(1)
print(b)

0


In [8]:
bb = np.random.randint(1, 5)
print(bb)

1


In [9]:
bbb = np.random.randint(1, 10, 5)
print(bbb)

[6 6 7 2 1]


In [10]:
bbbb = np.random.randint(1, 10, size=(3, 3))
print(bbbb)

[[7 8 6]
 [2 5 3]
 [2 1 2]]


**uniform() - This function generates floats random numbers in any range**

In [11]:
c = np.random.uniform()
print(c)

0.09956149880793397


In [12]:
cc = np.random.uniform(1, 5)
print(cc)

1.7279788217693826


In [13]:
ccc = np.random.uniform(1, 10, 5)
print(ccc)

[8.44709432 9.75978175 2.98260685 3.02324349 3.89011895]


In [14]:
cccc = np.random.uniform(1, 10, size=(3, 3))
print(cccc)

[[5.21132221 5.18842396 5.39344714]
 [4.80329168 1.57863145 1.92897575]
 [6.52141593 4.79821254 2.63379497]]


In [15]:
# Round off the values upto .2f decimal place
c = np.round(c, 2)
cc = np.round(cc, 2)
ccc = np.round(ccc, 2)
cccc = np.round(cccc, 2)
print('First :', c)
print('Second :', cc)
print('Third :', ccc)
print('Fourth :', cccc)

First : 0.1
Second : 1.73
Third : [8.45 9.76 2.98 3.02 3.89]
Fourth : [[5.21 5.19 5.39]
 [4.8  1.58 1.93]
 [6.52 4.8  2.63]]


**ranodm() - This function generates random numbers between 0 to 1, similar to rand() function but in a constrained way**

In [16]:
e = np.random.random()
print(e)

0.7557935468749449


In [17]:
ee = np.random.random(3)
print(ee)

[0.41407126 0.31317667 0.37910001]


In [18]:
eee = np.random.random((3, 3))
print(eee)

[[0.74113542 0.55572733 0.48042472]
 [0.27810082 0.38566907 0.330248  ]
 [0.72245858 0.01236756 0.43375766]]


In [19]:
# Round off the values upto .2f decimal place
e = np.round(e, 2)
ee = np.round(ee, 2)
eee = np.round(eee, 2)
print('First :', e)
print('Second :', ee)
print('Third :', eee)

First : 0.76
Second : [0.41 0.31 0.38]
Third : [[0.74 0.56 0.48]
 [0.28 0.39 0.33]
 [0.72 0.01 0.43]]
