**Import Libraries**

In [1]:
import numpy as np

- min, max
- mean
- median
- average
- variance
- standard deviation

In [2]:
a = np.array([[1,2,3,4],
              [7,6,2,0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


**min, max**

In [3]:
print('Minimum :', np.min(a))   # minimum element
print('Maximum :', np.max(a))

Minimum : 0
Maximum : 7


In [4]:
# Specify axis for direction in case of multidim array
print(np.min(a, axis=0))
print(np.min(a, axis=1))

[1 2 2 0]
[1 0]


**mean, median, average**

In [5]:
# Mean, Average of all the elements
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)
n = sum(b)//5
print(n)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [6]:
# Median
c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [7]:
# Mean vs Average(It is weighted)
print(np.mean(c))

# Weights
w = np.array([1,2,3,4,5])
print(np.average(c, weights = w))

w = np.array([1,1,1,1,1])
print(np.average(c, weights = w))

2.4
2.066666666666667
2.4


In [8]:
# Standard Deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

# Inbuilt Function for standard deviaton
dev = np.std(c)
print(dev)

# Variance
print(myStd**2)

# Inbuilt Variance
print(np.var(c))

1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
