**Import Libraries**

In [1]:
import numpy as np

**Arrays**

In [2]:
# 1D-Array
x = np.array([1,2,3,4,5])
print(x)
print(type(x))
print(x.shape)
print(x.shape[0])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
5


In [3]:
# 2D-Array
y = np.array([[1,2,3,4,5],
              [6, 7, 8, 9, 10]])
print(y)
print(type(y))
print(y.shape)
print(y.shape[0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
(2, 5)
2


In [4]:
# Create array of zeros (0)
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Create array of ones (1)
o = np.ones((3, 3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# Array as some constant
c = np.full((3, 3), 5)
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


**Matrix**

In [7]:
# Identity Matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
# Random Matrix - We can create random matrix using all these function
# 1. rand() : gives numbers between 0 and 1
# 2. random() : gives numbers between 0 and 1
# 3. randint() : gives positive integers numbers between 0 to infinity
# 4. uniform() : gives float integers numbers between (-)inifnity to (+)infinity

arr1 = np.random.randint(1, 10, size=(2, 2))
arr1 = np.round(arr1, 2)
print(arr1)
print('\n')
arr2 = np.random.randint(1, 10, size=(2, 2))
arr2 = np.round(arr2, 2)
print(arr2)

[[3 5]
 [5 8]]


[[5 9]
 [3 7]]


**Mathematical Operations - Addition, Subtraction, Multiplication, Division**

In [9]:
# Element Wise Operations
print('Addition')
print(arr1 + arr2)
print(np.add(arr1, arr2))
print("\n")

print('Subtraction')
print(arr1 - arr2)
print(np.subtract(arr1, arr2))
print("\n")

print('Multiplication')
print(arr1 * arr2)
print(np.multiply(arr1, arr2))
print("\n")

print('Division')
print(arr1 / arr2)
print(np.divide(arr1, arr2))

Addition
[[ 8 14]
 [ 8 15]]
[[ 8 14]
 [ 8 15]]


Subtraction
[[-2 -4]
 [ 2  1]]
[[-2 -4]
 [ 2  1]]


Multiplication
[[15 45]
 [15 56]]
[[15 45]
 [15 56]]


Division
[[0.6        0.55555556]
 [1.66666667 1.14285714]]
[[0.6        0.55555556]
 [1.66666667 1.14285714]]


In [10]:
# Element wise Square Root
print(np.sqrt(arr1))
print('\n')
print(np.sqrt(arr2))

[[1.73205081 2.23606798]
 [2.23606798 2.82842712]]


[[2.23606798 3.        ]
 [1.73205081 2.64575131]]


**Matrix Multiplication**

In [11]:
# Dot Product
print('arr1 \n', arr1)
print('arr2 \n', arr2)

print('\n')

print(arr1.dot(arr2))
print(np.dot(arr1, arr2))

arr1 
 [[3 5]
 [5 8]]
arr2 
 [[5 9]
 [3 7]]


[[ 30  62]
 [ 49 101]]
[[ 30  62]
 [ 49 101]]


In [12]:
# Multiplication(Dot product) of Vectors => Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [13]:
# Sum of Array
print(a)
print(sum(a))

[1 2 3 4]
10


In [14]:
# Adding Matrix Row Wise and Column Wise
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x)
print('Sum :', np.sum(x))
print('Row :', np.sum(x,axis=0))  # Direction = row
print('Column :', np.sum(x,axis=1))  # Direction = column

[[1 2]
 [3 4]]
Sum : 10
Row : [4 6]
Column : [3 7]


In [15]:
# Stacking of Arrays
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [16]:
print(x)
y = y**2
print(y)

[[1 2]
 [3 4]]
[[25 36]
 [49 64]]


In [17]:
print(np.stack((x, y),axis=0))

[[[ 1  2]
  [ 3  4]]

 [[25 36]
  [49 64]]]


In [18]:
print(np.stack((x, y),axis=1))

[[[ 1  2]
  [25 36]]

 [[ 3  4]
  [49 64]]]


In [19]:
# Reshaping of Array
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

In [20]:
print(a)
a = a.reshape((2, 2))
print(a)

[1 2 3 4]
[[1 2]
 [3 4]]


In [21]:
b = b.reshape(-1, 1)
print(b)

[[1]
 [2]
 [3]
 [4]]
